//
//  DraggableViewController.swift
//  OpalAiTestApp
//
//  Created by Milad on 7/5/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import UIComponents

protocol DraggableDisplayLogic: AnyObject
{
  func displaySomething(viewModel: Draggable.Something.ViewModel)
}

class DraggableViewController: UITableViewController, DraggableDisplayLogic
{
    
    var interactor: DraggableBusinessLogic?
    var router: (NSObjectProtocol & DraggableRoutingLogic & DraggableDataPassing)?
    
    let cellData = [
        ("Info", "Hagstrasse 8, 9497 Triesenberg, Liechtenstein", "Info_Square"),
        ("image and note", "no image is submitted", "Image"),
        ("Materials", "Select materials", "dollar-square"),
        ("Project total expenses", "choose your materials to calculate", "dollar-square")
    ]
    //var tableView: UITableView!
    
    
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = DraggableInteractor()
        let presenter = DraggablePresenter()
        let router = DraggableRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        view.backgroundColor = UIColor(red: 250/255, green: 250/255, blue: 250/255, alpha: 1)
        tableView.register(DraggableViewTableViewCell.self, forCellReuseIdentifier: "CustomCell")
    }
        
        
        
        // MARK: Do something
        
        //@IBOutlet weak var nameTextField: UITextField!
        
        func doSomething()
        {
            let request = Draggable.Something.Request()
            interactor?.doSomething(request: request)
        }
        
        func displaySomething(viewModel: Draggable.Something.ViewModel)
        {
            //nameTextField.text = viewModel.name
        }
    }

extension DraggableViewController {
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return cellData.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "CustomCell", for: indexPath) as! DraggableViewTableViewCell
        let data = cellData[indexPath.row]
        cell.configureCell(text: data.0, secondaryText: data.1, imageName: data.2)
        cell.selectionStyle = .none
        cell.accessoryType = .disclosureIndicator
        cell.backgroundColor = UIColor(red: 250/255, green: 250/255, blue: 250/255, alpha: 1)
        return cell
    }
}


