//
//  DraggableInteractor.swift
//  OpalAiTestApp
//
//  Created by Milad on 7/5/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DraggableBusinessLogic
{
  func doSomething(request: Draggable.Something.Request)
}

protocol DraggableDataStore
{
  //var name: String { get set }
}

class DraggableInteractor: DraggableBusinessLogic, DraggableDataStore
{
  var presenter: DraggablePresentationLogic?
  var worker: DraggableWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Draggable.Something.Request)
  {
    worker = DraggableWorker()
    worker?.doSomeWork()
    
    let response = Draggable.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
