//
//  DraggablePresenter.swift
//  OpalAiTestApp
//
//  Created by Milad on 7/5/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DraggablePresentationLogic
{
  func presentSomething(response: Draggable.Something.Response)
}

class DraggablePresenter: DraggablePresentationLogic
{
  weak var viewController: DraggableDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Draggable.Something.Response)
  {
    let viewModel = Draggable.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
