//
//  ScanViewerWorker.swift
//  OpalAiTestApp
//
//  Created by Milad on 7/4/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RoomPlan

class ScanViewerWorker
{
    
    func get3DPlan() -> URL?
    {
        return loadUSDZModel()
    }
    func get2Dplan() -> CapturedRoom? {
        return loadAndParseSampleJSON()
    }
    func get3DSample() -> URL?
    {
        return loadUSDZSampleModel()
    }
    
    private func loadAndParseSampleJSON() -> CapturedRoom? {
        do {
            guard let filePath = Bundle.main.path(forResource: "sample", ofType: "json") else {
                print("Error: sample.json not found")
                return nil
            }
            
            let jsonData = try Data(contentsOf: URL(fileURLWithPath: filePath))
            
            let decoder = JSONDecoder()
            let roomData = try decoder.decode(CapturedRoom.self, from: jsonData)
            
            return roomData
        } catch {
            print("Error loading or decoding JSON: \(error)")
            return nil
        }
    }
    
    func loadUSDZModel() -> URL? {
        guard let url = Bundle(for: type(of: self)).url(forResource: "exportedRoom", withExtension: "usdz") else {
            fatalError("Failed to find USDZ file in the bundle")
        }
        return url
    }
    func loadUSDZSampleModel() -> URL? {
        guard let url = Bundle(for: type(of: self)).url(forResource: "sample", withExtension: "usdz") else {
            fatalError("Failed to find USDZ file in the bundle")
        }
        return url
    }
}
