//
//  ScanViewerViewController.swift
//  OpalAiTestApp
//
//  Created by Milad on 7/4/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import UIComponents
import UIScanViewer

protocol ScanViewerDisplayLogic: class
{
  func displaySomething(viewModel: ScanViewer.Something.ViewModel)
}

class ScanViewerViewController: UIViewController, ScanViewerDisplayLogic
{
  var interactor: ScanViewerBusinessLogic?
  var router: (NSObjectProtocol & ScanViewerRoutingLogic & ScanViewerDataPassing)?

    var coder: NSCoder!
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
      self.coder = aDecoder
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ScanViewerInteractor()
    let presenter = ScanViewerPresenter()
    let router = ScanViewerRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  override func viewDidLoad()
  {
    super.viewDidLoad()
      self.view.backgroundColor = UIColor(resource: .background)
      setupPageVIewController()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
    func setupPageVIewController() {
        // Instantiate the PageViewController
        guard let pageViewController = PageViewController(coder: self.coder) else { fatalError() }
        pageViewController.orderedViewControllers = [UIScanViewerController(), UIScanViewerController()]
        
        // Add it as a child view controller
        addChild(pageViewController)
        
        // Set the frame or constraints to make it cover the entire view
        pageViewController.view.frame = view.bounds
        pageViewController.view.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(pageViewController.view)
        
        NSLayoutConstraint.activate([
            pageViewController.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            pageViewController.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            pageViewController.view.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor,constant: 0),
            pageViewController.view.bottomAnchor.constraint(equalTo: view.bottomAnchor)
        ])
        
        // Notify the PageViewController that it has been moved to the parent
        pageViewController.didMove(toParent: self)
    }
    
  func doSomething()
  {
    let request = ScanViewer.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: ScanViewer.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
