//
//  ScanViewerPresenter.swift
//  OpalAiTestApp
//
//  Created by Milad on 7/4/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ScanViewerPresentationLogic
{
  func presentPlans(response: ScanViewer.PlanModel.Response)
}

class ScanViewerPresenter: ScanViewerPresentationLogic
{
  weak var viewController: ScanViewerDisplayLogic?
  
  // MARK: Do something
  
  func presentPlans(response: ScanViewer.PlanModel.Response)
    {
        let viewModel = ScanViewer.PlanModel.ViewModel(plan2D: response.plan2D, plan3D: response.plan3D, sample3D: response.sample3D)
        viewController?.displayPlans(viewModel: viewModel)
  }
}
