//
//  ScanViewerInteractor.swift
//  OpalAiTestApp
//
//  Created by Milad on 7/4/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ScanViewerBusinessLogic
{
  func doSomething(request: ScanViewer.Something.Request)
}

protocol ScanViewerDataStore
{
  //var name: String { get set }
}

class ScanViewerInteractor: ScanViewerBusinessLogic, ScanViewerDataStore
{
  var presenter: ScanViewerPresentationLogic?
  var worker: ScanViewerWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ScanViewer.Something.Request)
  {
    worker = ScanViewerWorker()
    worker?.doSomeWork()
    
    let response = ScanViewer.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
